name: Build Astro site

on:
  push:
    branches:
      - main
      - astroisme
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      # 3. Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Compile le site Astro
      - name: Build site
        run: npm run build

      # 5. (optionnel) Archive le dossier dist pour l’utiliser ensuite (ex: déploiement)
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-dist
          path: dist
